title: Medeiros' Stack
description: My Personal Stack
author: Daniel Medeiros
github: https://github.com/medeiros
about: Software engineer
#disqus_shortname: medeiros-1
#google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/profile-picture-daniel.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    #- icon: fa-facebook
    #  link: "#"
    - icon: fa-github
      link: "https://github.com/medeiros"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/dmassis"
    - icon: fa-stack-exchange
      link: "https://stackoverflow.com/users/5457366/medeiros"
    - icon: fa-twitter
      link: "https://twitter.com/dnlmed"
    - icon: fa-envelope
      link: "mailto:daniel@arneam.com"
share:
  twitter_username: dnlmed
  #fb_appid: 1234567890123456

#urls:
    #- text: Home
    #  url: /
    #- text: About Me
    #  url: /about/
    #- text: My Projects
    #  url: /projects/
    #- text: XML Feed
    #  url: /feed.xml

url: "http://medeiros.arneam.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
