# Site Settings
title:               Medeiros
tagline:             software engineering
description:
baseurl:            ""
url:                "https://medeiros.arneam.com"
github:
  url:               #"https://medeiros.github.io"
author:
  name:              "Daniel Medeiros"
  email:             "daniel@arneam.com"
  twitter:           #"dnlmed"
  instagram:         #""
  github:            "medeiros"
  facebook:          #""
  linkedin:          "dmassis"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact
image:
  profilepicture:    profile-picture-daniel.jpg
post:
  tagline:           "A software engineer who refactor its thoughts through writing."
  touch-message:     "If you'd like to get in touch, feel free to #contact# me"
paginate:            5
disqus:              medeiros-1

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
